import React, { useState, useEffect } from 'react';
import Page from '../components/common/Page';
import Card from '../components/common/Card';
import type { WeatherAlert, AlertSeverity, AlertStatus } from '../types/weather';
import { getAlerts } from '../services/weatherApi';

const SEVERITY_ORDER: AlertSeverity[] = ['Critical', 'High', 'Medium', 'Low'];

const severityConfig = {
  Critical: { bg: 'bg-red-900/50',    border: 'border-red-700',    text: 'text-red-300',    badge: 'bg-red-700 text-white' },
  High:     { bg: 'bg-orange-900/50', border: 'border-orange-700', text: 'text-orange-300', badge: 'bg-orange-700 text-white' },
  Medium:   { bg: 'bg-yellow-900/50', border: 'border-yellow-700', text: 'text-yellow-300', badge: 'bg-yellow-700 text-white' },
  Low:      { bg: 'bg-blue-900/50',   border: 'border-blue-700',   text: 'text-blue-300',   badge: 'bg-blue-700 text-white' },
};

const statusConfig: Record<AlertStatus, string> = {
  Active:     'bg-green-900/50 text-green-300 border border-green-700',
  Monitoring: 'bg-yellow-900/50 text-yellow-300 border border-yellow-700',
  Resolved:   'bg-gray-700/50 text-gray-400 border border-gray-600',
};

const AlertCard: React.FC<{ alert: WeatherAlert }> = ({ alert }) => {
  const cfg = severityConfig[alert.severity];
  return (
    <div className={`rounded-xl border p-4 ${cfg.bg} ${cfg.border}`}>
      <div className="flex items-start justify-between gap-3 mb-2">
        <div className="flex items-start gap-3 min-w-0">
          <span className="text-2xl flex-shrink-0">{alert.icon}</span>
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <h3 className={`font-bold text-base ${cfg.text}`}>{alert.title}</h3>
              <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${cfg.badge}`}>{alert.severity}</span>
              <span className={`text-xs px-2 py-0.5 rounded-full ${statusConfig[alert.status]}`}>{alert.status}</span>
            </div>
            <p className="text-gray-400 text-sm mt-0.5">{alert.locationName}</p>
          </div>
        </div>
        <span className="text-gray-400 text-xs text-right flex-shrink-0 whitespace-nowrap">
          {new Date(alert.timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>

      <p className="text-gray-300 text-sm ml-10 leading-relaxed">{alert.description}</p>

      <div className="flex flex-wrap gap-3 mt-3 ml-10 text-xs text-gray-400">
        <span className="flex items-center gap-1">
          ⏱ <span>Prediction horizon: <strong className={cfg.text}>{alert.predictionHorizon}</strong></span>
        </span>
        <span className="flex items-center gap-1">
          📊 <span>Triggered: <strong className="text-white">{alert.parameterTriggered}</strong></span>
        </span>
        <span className="flex items-center gap-1">
          🕐 <span>Updated: {new Date(alert.updatedAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</span>
        </span>
      </div>
    </div>
  );
};

const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<WeatherAlert[]>([]);
  const [filterSeverity, setFilterSeverity] = useState<AlertSeverity | 'All'>('All');
  const [filterStatus, setFilterStatus] = useState<AlertStatus | 'All'>('All');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getAlerts().then(data => { setAlerts(data); setLoading(false); });
  }, []);

  const filtered = alerts.filter(a =>
    (filterSeverity === 'All' || a.severity === filterSeverity) &&
    (filterStatus   === 'All' || a.status   === filterStatus)
  );

  const active   = alerts.filter(a => a.status === 'Active');
  const resolved = alerts.filter(a => a.status === 'Resolved');

  return (
    <Page title="Early Warning & Alerts">
      {/* Demo notice */}
      <div className="flex items-center gap-2 bg-amber-900/30 border border-amber-800 rounded-lg px-4 py-2.5 text-amber-300 text-xs">
        <span>⚠️</span>
        <span><strong>DEMO DATA ONLY</strong> — Warnings shown are model demonstration signals. When live backend is connected, real alerts generated by the WeatherNow AI model will populate this page.</span>
      </div>

      {/* Summary stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <div className="bg-gray-800 border border-gray-700/80 rounded-xl p-4">
          <p className="text-gray-400 text-xs uppercase tracking-wider">Total Alerts</p>
          <p className="text-3xl font-bold text-white mt-1">{alerts.length}</p>
        </div>
        <div className="bg-red-900/30 border border-red-800/80 rounded-xl p-4">
          <p className="text-red-400 text-xs uppercase tracking-wider">Active</p>
          <p className="text-3xl font-bold text-red-300 mt-1">{active.length}</p>
        </div>
        <div className="bg-gray-700/30 border border-gray-700/80 rounded-xl p-4">
          <p className="text-gray-400 text-xs uppercase tracking-wider">Resolved</p>
          <p className="text-3xl font-bold text-gray-300 mt-1">{resolved.length}</p>
        </div>
        <div className="bg-orange-900/30 border border-orange-800/80 rounded-xl p-4">
          <p className="text-orange-400 text-xs uppercase tracking-wider">Critical Active</p>
          <p className="text-3xl font-bold text-orange-300 mt-1">
            {alerts.filter(a => a.severity === 'Critical' && a.status === 'Active').length}
          </p>
        </div>
      </div>

      {/* Filters */}
      <Card title="">
        <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center">
          <div>
            <label className="text-gray-400 text-xs uppercase tracking-wider block mb-1">Severity</label>
            <div className="flex gap-1 flex-wrap">
              {(['All', ...SEVERITY_ORDER] as const).map(s => (
                <button key={s} onClick={() => setFilterSeverity(s)}
                  className={`text-xs px-2.5 py-1 rounded-full font-medium transition-colors ${
                    filterSeverity === s
                      ? s === 'All' ? 'bg-gray-600 text-white' :
                        s === 'Critical' ? 'bg-red-600 text-white' :
                        s === 'High'     ? 'bg-orange-600 text-white' :
                        s === 'Medium'   ? 'bg-yellow-600 text-white' : 'bg-blue-600 text-white'
                      : 'bg-gray-700 text-gray-400 hover:text-white'
                  }`}
                >{s}</button>
              ))}
            </div>
          </div>
          <div>
            <label className="text-gray-400 text-xs uppercase tracking-wider block mb-1">Status</label>
            <div className="flex gap-1 flex-wrap">
              {(['All', 'Active', 'Monitoring', 'Resolved'] as const).map(s => (
                <button key={s} onClick={() => setFilterStatus(s)}
                  className={`text-xs px-2.5 py-1 rounded-full font-medium transition-colors ${
                    filterStatus === s ? 'bg-teal-600 text-white' : 'bg-gray-700 text-gray-400 hover:text-white'
                  }`}
                >{s}</button>
              ))}
            </div>
          </div>
          <span className="text-gray-400 text-xs ml-auto">{filtered.length} alerts shown</span>
        </div>
      </Card>

      {/* Alert list */}
      {loading ? (
        <div className="flex justify-center py-12">
          <svg className="animate-spin h-8 w-8 text-teal-400" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.length === 0 ? (
            <div className="text-center py-12 text-gray-400">
              <p className="text-4xl mb-3">✅</p>
              <p className="font-medium">No alerts matching current filters</p>
            </div>
          ) : (
            filtered
              .sort((a, b) => {
                const sOrder = SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity);
                if (sOrder !== 0) return sOrder;
                return new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime();
              })
              .map(alert => <AlertCard key={alert.id} alert={alert} />)
          )}
        </div>
      )}

      {/* Historical alerts table */}
      <Card title="">
        <h3 className="text-white font-semibold mb-3 flex items-center gap-2">
          📋 Alert History Log
          <span className="text-xs text-gray-400 font-normal">(Last 24 Hours)</span>
        </h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="border-b border-gray-700">
              <tr className="text-gray-400 text-xs uppercase tracking-wider">
                <th className="py-2 px-3">Time</th>
                <th className="py-2 px-3">Alert</th>
                <th className="py-2 px-3">Location</th>
                <th className="py-2 px-3">Severity</th>
                <th className="py-2 px-3">Status</th>
                <th className="py-2 px-3">Trigger Condition</th>
              </tr>
            </thead>
            <tbody>
              {alerts.map(a => (
                <tr key={a.id} className="border-b border-gray-700/60 last:border-0 hover:bg-gray-700/30 transition-colors">
                  <td className="py-2.5 px-3 text-gray-400 whitespace-nowrap">
                    {new Date(a.timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
                  </td>
                  <td className="py-2.5 px-3 text-gray-200 font-medium">{a.icon} {a.title}</td>
                  <td className="py-2.5 px-3 text-gray-400">{a.locationName}</td>
                  <td className="py-2.5 px-3">
                    <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${severityConfig[a.severity].badge}`}>
                      {a.severity}
                    </span>
                  </td>
                  <td className="py-2.5 px-3">
                    <span className={`text-xs px-2 py-0.5 rounded-full ${statusConfig[a.status]}`}>
                      {a.status}
                    </span>
                  </td>
                  <td className="py-2.5 px-3 text-gray-400 text-xs">{a.parameterTriggered}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </Page>
  );
};

export default AlertsPage;
